apiVersion: v1
kind: Pod
metadata:
  name: data1
  labels:
    name: db
spec:
  containers:
  - name: data
    image: mysql
    resources:
          requests:
             memory: "500M"
             cpu: "500m"
          limits:
             memory: "500M"
             cpu: "500m"
    env:
      - name: MYSQL_ROOT-PASSWORD
        value: admin     

