apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
  - name: db
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
             configMapKeyRef:
                      name: cm1
                      key: MYSQL_ROOT_PASSWORD     

