apiVersion: apps/v1
kind: Deployment 
metadata:
    name: web1-app-rs
spec:
    template:
        metadata:
             name: uv1
             labels:
               name: rs
        spec:        
            containers:
            - name: uv1
              image: nginx
    selector:
      matchLabels:
         name: rs
    replicas: 3
