apiVersion: v1
kind: ReplicationController
metadata:
    name: web2-app-rc
spec:
    template:
        metadata:
             name: uv1
             labels:
               name: xyz
        spec:        
            containers:
            - name: uv1
              image: nginx
    selector:
        name: xyz     
    replicas: 5
