apiVersion: v1
kind: Pod
metadata:
  name: tolerated
  labels:
    name: genius
spec:
  containers:
  - name: tolerated
    image: nginx
  tolerations:
        - key: "example-key"
          operator: "Exists"
          effect: "NoSchedule"    
